/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alarmclockclient;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Observable;
import java.util.Observer;
import java.util.regex.Pattern;
import javafx.scene.control.RadioButton;
import javax.swing.JRadioButton;

/**
 *
 * @author RobinBergseth
 */
public class AlarmClockGUI extends javax.swing.JFrame implements Observer {

    private AlarmData data;
    private Client client;
    private final String[] alarmCommand = {"Alarm1", "Alarm2"};
    private JRadioButton[] weekdays;

    /**
     * Creates new form AlarmClockGUI
     */
    public AlarmClockGUI(AlarmData ad) {
        data = ad;
        (new Thread(client = new Client(ad))).start();
        initComponents();
        weekdays = new JRadioButton[]{sunday, monday, tuesday, wednesday, thursday, friday, saturday};
        String[] alarms = {"Alarm 1", "Alarm 2"};
        for (int x = 0; x < 24; x++) {
            hourSelect.addItem(x);
        }
        for (int x = 0; x < 60; x++) {
            minuteSelect.addItem(x);
        }
        for (String s : alarms) {
            alarmSelect.addItem(s);
        }
        setAlarmValues();
        setComboBoxValues();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                client.send("quit");
                client.closeConnection();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alarm1Text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alarm2Text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alarmSelect = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        hourSelect = new javax.swing.JComboBox();
        minuteSelect = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        monday = new javax.swing.JRadioButton();
        tuesday = new javax.swing.JRadioButton();
        wednesday = new javax.swing.JRadioButton();
        thursday = new javax.swing.JRadioButton();
        friday = new javax.swing.JRadioButton();
        saturday = new javax.swing.JRadioButton();
        sunday = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        jLabel1.setText("Alarm clock");

        jLabel2.setText("Alarm 1");

        alarm1Text.setEditable(false);
        alarm1Text.setText("jTextField1");

        jLabel3.setText("Alarm 2");

        alarm2Text.setEditable(false);
        alarm2Text.setText("jTextField1");

        jLabel4.setText("Set alarm");

        alarmSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                alarmSelectItemStateChanged(evt);
            }
        });

        jLabel5.setText("Hour");

        jLabel6.setText("Minute");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Days");

        monday.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        monday.setText("Monday");
        monday.setMaximumSize(new java.awt.Dimension(65, 23));
        monday.setMinimumSize(new java.awt.Dimension(65, 23));
        monday.setPreferredSize(new java.awt.Dimension(65, 23));

        tuesday.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tuesday.setText("Tuesday");

        wednesday.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        wednesday.setText("Wednesday");
        wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayActionPerformed(evt);
            }
        });

        thursday.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        thursday.setText("Thursday");

        friday.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        friday.setText("Friday");

        saturday.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        saturday.setText("Saturday");

        sunday.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        sunday.setText("Sunday");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alarm1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alarm2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alarmSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hourSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(minuteSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(monday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thursday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(friday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saturday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sunday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarm1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarm2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuesday)
                    .addComponent(wednesday)
                    .addComponent(thursday)
                    .addComponent(friday)
                    .addComponent(saturday)
                    .addComponent(sunday))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        changeAlarms();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void wednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayActionPerformed

    private void alarmSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_alarmSelectItemStateChanged
        setDaysValues();
        setComboBoxValues();

    }//GEN-LAST:event_alarmSelectItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alarm1Text;
    private javax.swing.JTextField alarm2Text;
    private javax.swing.JComboBox alarmSelect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton friday;
    private javax.swing.JComboBox hourSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox minuteSelect;
    private javax.swing.JRadioButton monday;
    private javax.swing.JRadioButton saturday;
    private javax.swing.JRadioButton sunday;
    private javax.swing.JRadioButton thursday;
    private javax.swing.JRadioButton tuesday;
    private javax.swing.JRadioButton wednesday;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        System.out.println("Update");
        if (o instanceof AlarmData) {
            AlarmData ad = (AlarmData) o;
            String[] alarms = ad.getAlarms();
            setAlarmValues();
        }
    }

    private void changeAlarms() {
        int alarm = alarmSelect.getSelectedIndex();
        int hour = (int) hourSelect.getSelectedItem();
        int minute = (int) minuteSelect.getSelectedItem();
        String time = "";
        if (hour < 10) {
            time += "0" + hour;
        } else {
            time += hour;
        }
        time += ".";
        if (minute < 10) {
            time += "0" + minute;
        } else {
            time += minute;
        }
        String send = "Set " + alarmCommand[alarm] + " " + time + " " + getWeekdays();
        System.out.println(send);
        client.send(send);
    }

    private void setAlarmValues() {
        String[] alarmValues = data.getAlarms();
        alarm1Text.setText(alarmValues[0]);
        alarm2Text.setText(alarmValues[1]);
    }

    private void setDaysValues() {
        int index = alarmSelect.getSelectedIndex();
        String[] daysValues = data.getDays();
        String[] days = daysValues[index].split(",");
        sunday.setSelected(stringToBool(days[0]));
        monday.setSelected(stringToBool(days[1]));
        tuesday.setSelected(stringToBool(days[2]));
        wednesday.setSelected(stringToBool(days[3]));
        thursday.setSelected(stringToBool(days[4]));
        friday.setSelected(stringToBool(days[5]));
        saturday.setSelected(stringToBool(days[6]));

    }

    private boolean stringToBool(String s) {
        int i = Integer.parseInt(s);
        boolean b = (i != 0);
        return b;
    }

    private String getWeekdays() {
        String ret = "";
        for (JRadioButton r : weekdays) {
            if (ret.equals("")) {
                if (r.isSelected()) {
                    ret += "1";
                } else {
                    ret += "0";
                }
            } else {
                if (r.isSelected()) {
                    ret += ",1";
                } else {
                    ret += ",0";
                }
            }
        }
        return ret;
    }

    private void setComboBoxValues() {
        String[] alarmValues = data.getAlarms();
        String[] a1HM = alarmValues[0].split(Pattern.quote("."));
        String[] a2HM = alarmValues[1].split(Pattern.quote("."));
        if (alarmSelect.getSelectedItem() instanceof String) {
            String index = (String) alarmSelect.getSelectedItem();
            if (index.equals("Alarm 1")) {
                int h = Integer.parseInt(a1HM[0]);
                int m = Integer.parseInt(a1HM[1]);
                if (hourSelect.getItemCount() >= h) {
                    hourSelect.setSelectedIndex(h);
                }
                if (minuteSelect.getItemCount() >= m) {
                    minuteSelect.setSelectedIndex(m);
                }
            } else if (index.equals("Alarm 2")) {
                int h = Integer.parseInt(a2HM[0]);
                int m = Integer.parseInt(a2HM[1]);
                if (hourSelect.getItemCount() >= h) {
                    hourSelect.setSelectedIndex(h);
                }
                if (minuteSelect.getItemCount() >= m) {
                    minuteSelect.setSelectedIndex(m);
                }
            }
        }
    }

}
